spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/asyncweb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework: INFO
