services:

  asyncweb_db:
    image: postgres
    restart: always
    networks:
      - asyncweb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=asyncweb

networks:
  asyncweb:
    name: "asyncweb"
