logging:
  level:
    org.springframework: INFO
    org.springdoc: INFO
    org.springframework.r2dbc: INFO

spring:
  application:
    name: asyncweb
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  profiles:
    active: development
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/asyncweb
    username: asyncweb
    password: password

